include $(GOROOT)/src/Make.inc

TARG=MyBot
GOFILES=\
	ants.go\
	country.go\
	fair_locator.go\
	locset.go\
	main.go\
	map.go\
	path.go\
	tasks.go\
	torus.go\
	MyBot.go\

include $(GOROOT)/src/Make.cmd
